[server]
headless = true
port = 8501
maxUploadSize = 200

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#FFD700"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F8FF"
textColor = "#2F4F4F"
font = "sans serif"

[client]
caching = true
displayEnabled = true